const $=s=>document.querySelector(s);
const pontok=[72,48,24,12,6,3,1];
const pct=x=>Number.isFinite(+x)?(+x*100).toFixed(1)+'%':'–';
const signedPct=x=>Number.isFinite(+x)?((+x>=0?'+':'')+(+x*100).toFixed(1)+'%'):'–';
const dt=x=>x?new Date(x).toLocaleString('hu-HU'):'–';
const SPORT={soccer:'Labdarúgás',basketball:'Kosárlabda',baseball:'Baseball',american_football:'Amerikai futball',hockey:'Jégkorong',tennis:'Tenisz',table_tennis:'Asztalitenisz',handball:'Kézilabda',volleyball:'Röplabda',beach_volleyball:'Strandröplabda',cricket:'Krikett',rugby_union:'Rögbi unió',rugby_league:'Rögbi liga',australian_rules:'Ausztrál futball',mma:'MMA',boxing:'Ökölvívás',kickboxing:'Kick-box',golf:'Golf',darts:'Darts',snooker:'Snooker',badminton:'Tollaslabda',squash:'Squash',water_polo:'Vízilabda',field_hockey:'Gyeplabda',floorball:'Floorball',bandy:'Bandy',futsal:'Futsal',beach_soccer:'Strandlabdarúgás',lacrosse:'Lacrosse',gaelic_football:'Gael futball',hurling:'Hurling',cycling:'Kerékpár',formula_1:'Formula–1',motogp:'MotoGP',motorsport:'Motorsport',athletics:'Atlétika',swimming:'Úszás',skiing:'Sí',biathlon:'Biatlon',ski_jumping:'Síugrás',speed_skating:'Gyorskorcsolya',curling:'Curling',bowls:'Golyósport',bowling:'Bowling',chess:'Sakk',esports:'E-sport',horse_racing:'Lóverseny',greyhound_racing:'Agárverseny'};
const sport=s=>SPORT[s]||String(s||'–').replaceAll('_',' ');
const piac=p=>({moneyline:'Győztes',h2h:'Győztes','1x2':'1X2',one_x_two:'1X2',match_winner:'Győztes',spread:'Pontelőny / ponthátrány',handicap:'Előny / hátrány',asian_handicap:'Ázsiai előny / hátrány',runline:'Futáselőny / hátrány',puckline:'Gólelőny / hátrány',total:'Összes pont/gól',team_total:'Csapat pont/gól',draw_no_bet:'Döntetlennél tét vissza',double_chance:'Két eredmény közül bármelyik',total_games:'Összes játék',total_sets:'Összes szett',total_points:'Összes pont',total_runs:'Összes futás',outright:'Végső győztes',race_winner:'Futamgyőztes',event_winner:'Versenyszám győztese'})[p]||String(p||'–').replaceAll('_',' ');
const edge=(p,m)=>Number.isFinite(+p)&&Number.isFinite(+m)?((+p-(+m))*100).toFixed(1)+' százalékpont':'–';
const ev=x=>Number.isFinite(+x)?(+x).toFixed(1)+'%':'–';
const stakePct=x=>Number.isFinite(+x)?(+x*100).toFixed(1)+'% a tesztkeretből':'–';
const resultPct=x=>{const stake=Number(x.tet_osszeg),profit=Number(x.nyereseg_veszteseg);return Number.isFinite(stake)&&stake>0&&Number.isFinite(profit)?((profit/stake>=0?'+':'')+(profit/stake*100).toFixed(1)+'%'):'–'};
async function J(p){const r=await fetch(p+'?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error(p+' HTTP '+r.status);return r.json()}

function betKartya(x,i){const forma=piac(x.piac);return `<article class="bet"><span class="rank">#${i+1}</span><span class="pill">${sport(x.sportag)}</span><span class="pill">${forma}</span><h3>${x.kimenetel||'–'}</h3><p class="muted mini"><b>Javasolt választás:</b> ${x.kimenetel||'–'}</p><div class="facts"><div class="fact">Szorzó<b>${x.szorzo??'–'}</b></div><div class="fact">A rendszer szerint ennyi az esélye<b>${pct(x.becsult_esely)}</b></div><div class="fact">A fogadóirodák szerint ennyi az esélye<b>${pct(x.piaci_esely)}</b></div><div class="fact">Mennyire biztos a rendszer a becslésben<b>${pct(x.megbizhatosag)}</b></div><div class="fact">A rendszer előnye a piaci becsléshez képest<b>${edge(x.becsult_esely,x.piaci_esely)}</b></div><div class="fact">Becsült hosszú távú előny<b>${ev(x.varhato_ertek_szazalek)}</b></div><div class="fact">Tesztben használt tét<b>${stakePct(x.tet_szazalek)}</b></div></div><p class="muted mini">Fogadóiroda: ${x.iroda||'–'} • Kiválasztás ideje: ${dt(x.dontesi_ido)} • Kezdés: ${dt(x.esemeny_ideje)}</p></article>`}

function eloHu(s){return ({PAPER_UTVONAL_ELO_BIZONYITOTT:'Teljesen kipróbálva élő adatokkal',MODELL_ELO_BIZONYITOTT:'Az elemzés élőben működik',AKTIV_MODELL_HIANYZIK:'Adat van, az elemzés még nem futott végig',ILLESZTES_HIANYZIK:'Az adatok megvannak, az összekapcsolás hiányzik',SPORTADAT_HIANYZIK:'Hiányzik a szükséges sportadat',VAR_AKTIV_ODDSRA:'Most nincs fogadható esemény'})[s]||String(s||'–').replaceAll('_',' ')}
function elszHu(s){return ({PAPER_ELSZAMOLHATO:'Az eredmény automatikusan feldolgozható',VERSENY_ADAPTER_KESZ_ELO_BIZONYITASRA_VAR:'Felkészítve, élő eredményre vár',EREDMENY_ELSZAMOLAS_ELO_BIZONYITASRA_VAR:'Az eredményfeldolgozás élő próbára vár'})[s]||String(s||'–').replaceAll('_',' ')}
function sportSor(x){const ok=!!x.statikus_szerzodes_rendben;const elo=x.elo_allapot==='PAPER_UTVONAL_ELO_BIZONYITOTT';return `<details><summary>${sport(x.sportag)} — ${elo?'TELJESEN KIPRÓBÁLVA':eloHu(x.elo_allapot)}</summary><div class="facts"><div class="fact">Előkészített fogadástípusok<b>${x.piacok_szama??0}</b></div><div class="fact">Eredmény feldolgozása<b>${elszHu(x.elszamolasi_allapot)}</b></div><div class="fact">Most elérhető szorzóadatok<b>${x.odds??0}</b></div><div class="fact">Most elérhető sportadatok<b>${x.sportadat??0}</b></div><div class="fact">Sikeresen összekapcsolt adatok<b>${x.ellenorzott??0}</b></div><div class="fact">Működő elemzések<b>${x.aktiv_modell??0}</b></div><div class="fact">Fogadásra alkalmas jelöltek<b>${x.portfolio??0}</b></div><div class="fact">Alapbeállítások<b class="${ok?'ok':'bad'}">${ok?'RENDBEN':'HIBÁS'}</b></div></div><p class="muted mini">Jelenlegi helyzet: ${eloHu(x.elo_allapot)}${x.kovetkezo_teendo?' • Következő lépés: '+x.kovetkezo_teendo:''}</p></details>`}

async function load(){
  try{
    const[a,p,m,s]=await Promise.all([J('data/allapot.json'),J('data/paper.json'),J('data/meresek.json'),J('data/sportagok.json').catch(()=>({sportagok:[],sportagok_szama:48,statikus_szerzodes_rendben:48,elo_allapotok:{}}))]);
    const lez=p.filter(x=>x.statusz!=='NYITOTT'),ny=p.filter(x=>x.statusz==='NYITOTT');
    const cel=Number(a.cel)||500,lezart=Number(a.lezart)||0,sportok=Array.isArray(a.sportagak)?a.sportagak:[...new Set(p.map(x=>x.sportag).filter(Boolean))];
    $('#minta').textContent=lezart+' / '+cel;$('#bar').style.width=Math.min(100,100*lezart/cel)+'%';$('#nyitott').textContent=Number.isFinite(+a.nyitott)?a.nyitott:ny.length;
    $('#sport48').textContent=(Number(a.statikus_sportag_ok)||Number(s.statikus_szerzodes_rendben)||0)+' / '+(Number(a.registry_sportag_db)||Number(s.sportagok_szama)||48);
    $('#sportelo').textContent=(Number(a.elo_paper_bizonyitott)||Number((s.elo_allapotok||{}).PAPER_UTVONAL_ELO_BIZONYITOTT)||0)+' / 48';
    $('#talalat').textContent=a.talalati_arany==null?'–':pct(a.talalati_arany);
    $('#penz').textContent=a.roi==null?'–':signedPct(a.roi);$('#penz').className='value '+(Number(a.roi)>=0?'ok':'bad');
    if($('#roi')){$('#roi').textContent=a.roi==null?'–':signedPct(a.roi);$('#roi').className='value '+(Number(a.roi)>=0?'ok':'bad')}
    $('#meresdb').textContent=Number(a.meresek)||0;
    $('#nyert').textContent=Number(a.nyert)||0;$('#vesztett').textContent=Number(a.vesztett)||0;$('#lezart').textContent=lezart;$('#hatra').textContent=Math.max(0,cel-lezart);
    $('#validacio').textContent=lezart>=cel?'Az 500 lezárt tesztfogadás összegyűlt. A rendszer végső értékelése elvégezhető.':'Még '+Math.max(0,cel-lezart)+' lezárt tesztfogadás szükséges. Az addigi százalékok még csak tájékoztató jellegűek.';
    $('#statusz').textContent=a.integritas_ok===false?'HIBÁT TALÁLT':'RENDBEN';$('#statusz').className='value '+(a.integritas_ok===false?'bad':'ok');
    $('#megjegyzes').textContent='Utolsó adatfrissítés: '+dt(a.frissitve);
    $('#sportdb').textContent=Number.isFinite(+a.sportag_db)?a.sportag_db:sportok.length;$('#sportlista').textContent=sportok.length?sportok.map(sport).join(', '):'Még nincs sportág a próbában.';
    $('#integritas').textContent=a.integritas_ok?'RENDBEN':'HIBÁT TALÁLT';$('#integritas').className='value '+(a.integritas_ok?'ok':'bad');if($('#integritasinfo'))$('#integritasinfo').textContent=a.integritas_ok?'Nem találtunk ismétlődő vagy hibás fogadási sort.':`Ismétlődő sor: ${a.duplikalt_sorok??0}, hibás azonosító: ${a.hibas_azonositoju_sorok??0}.`;
    $('#szamlalo').textContent=a.szamlalo_egyezik===true?'RENDBEN':a.szamlalo_egyezik===false?'ELTÉRÉS VAN':'–';$('#szamlalo').className='value '+(a.szamlalo_egyezik===true?'ok':a.szamlalo_egyezik===false?'bad':'');
    $('#kartyak').innerHTML=ny.length?ny.map(betKartya).join(''):'<div class="card empty">Jelenleg nincs aktív tesztfogadás.</div>';
    $('#lezartlista').innerHTML=lez.length?lez.slice().reverse().map(x=>`<details><summary>${sport(x.sportag)} — ${x.kimenetel||'–'} — ${x.eredmeny||x.statusz||'–'}</summary><div class="facts"><div class="fact">Fogadástípus<b>${piac(x.piac)}</b></div><div class="fact">Szorzó<b>${x.szorzo??'–'}</b></div><div class="fact">Eredmény<b>${x.eredmeny??'–'}</b></div><div class="fact">Eredmény a feltett tesztösszeghez képest<b>${resultPct(x)}</b></div><div class="fact">Felhasznált tesztkeret<b>${stakePct(x.tet_szazalek)}</b></div></div><p class="muted mini">Kiválasztás: ${dt(x.dontesi_ido)} • Kezdés: ${dt(x.esemeny_ideje)}</p></details>`).join(''):'<p class="muted">Még nincs lezárt tesztfogadás.</p>';
    const pontDb=a.meresi_pontok||{};$('#timeline').innerHTML=pontok.map(h=>{const n=Number(pontDb[String(h)]||0);return `<div class="tp ${n>0?'have':''}"><b>${h} órával előtte</b><br>${n} ellenőrzés</div>`}).join('');
    $('#meresosszefoglalo').textContent=`Összesen ${Number(a.meresek)||0} rögzített ellenőrzés. Ugyanazt a fogadást ugyanabban az időpontban csak egyszer számoljuk.`;
    $('#mereslista').innerHTML=m.length?m.slice().sort((a,b)=>new Date(b.adat_ideje)-new Date(a.adat_ideje)).map(x=>`<details><summary>${sport(x.sportag)} — ${x.kimenetel||'–'} — ${x.meresi_pont_ora??'–'} órával a kezdés előtt</summary><div class="facts"><div class="fact">Szorzó<b>${x.szorzo??'–'}</b></div><div class="fact">Rendszer becsült esélye<b>${pct(x.becsult_esely)}</b></div><div class="fact">Fogadóirodák becsült esélye<b>${pct(x.piaci_esely)}</b></div><div class="fact">Rendszer előnye<b>${edge(x.becsult_esely,x.piaci_esely)}</b></div></div><p class="muted mini">Ellenőrzés ideje: ${dt(x.adat_ideje)} • Kezdés: ${dt(x.esemeny_ideje)}</p></details>`).join(''):'<p class="muted">Még nincs időbeli ellenőrzés.</p>';
    const ea=s.elo_allapotok||{};$('#sportosszefoglalo').innerHTML=`<div class="fact">Mind a 48 sportág alapjai elkészültek<b>${s.statikus_szerzodes_rendben??0} / ${s.sportagok_szama??48}</b></div><div class="fact">Teljesen kipróbálva élő adatokkal<b>${ea.PAPER_UTVONAL_ELO_BIZONYITOTT??0}</b></div><div class="fact">Az elemzés élőben működik<b>${ea.MODELL_ELO_BIZONYITOTT??0}</b></div><div class="fact">Most nincs fogadható esemény<b>${ea.VAR_AKTIV_ODDSRA??0}</b></div><div class="fact">Hiányzik szükséges sportadat<b>${ea.SPORTADAT_HIANYZIK??0}</b></div>`;
    $('#sportlista48').innerHTML=(s.sportagak||[]).length?s.sportagak.map(sportSor).join(''):'<p class="muted">A részletes sportáglista a következő frissítéskor jelenik meg.</p>';
    $('#frissites').textContent='frissítve: '+dt(a.frissitve);
  }catch(e){$('#frissites').textContent='adatbetöltési hiba';$('#statusz').textContent='ADATBETÖLTÉSI HIBA';$('#statusz').className='value bad';console.error(e)}
}
load();
setInterval(load,60000);
